{"sid": "d233d5a9d1454065b38bc2a3a6daaa5a", "uid": null, "qid": "2e5a7f870d2e42bd88a2bf8ce982766f", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [2e5a7f870d2e42bd88a2bf8ce982766f]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    agent = Agent('gemini',\"TEST_USER\",session_id ,generator)\n  File \"/openfabric/app/Agent/agent.py\", line 28, in __init__\n    Agent._sessionsManager.add_session(session_id=session_id)\n  File \"/openfabric/app/Agent/agent.py\", line 263, in add_session\n    session_id = cls.generate_session_id()\nTypeError: generate_session_id() missing 1 required positional argument: 'cls'\n", "created_at": "2025-06-30T09:52:05.454943"}], "status": "FAILED", "created_at": "2025-06-30T09:52:04.852810", "updated_at": "2025-06-30T09:52:05.454988", "finished": true}