{"sid": "dbcc29a01a7d4c33ba7694ceeaf27dfb", "uid": null, "qid": "3c65f9b8f40c4f9ba2243cae2a59f76c", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [3c65f9b8f40c4f9ba2243cae2a59f76c]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 76, in Exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 129, in process\n    self.read_memory(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 94, in read_memory\n    summary = resp[\"summary\"]\nKeyError: 'summary'\n", "created_at": "2025-06-29T06:14:42.728993"}], "status": "FAILED", "created_at": "2025-06-29T06:14:41.306643", "updated_at": "2025-06-29T06:14:42.729037", "finished": true}