{"sid": "bfc21779399b4545832ec6b1407c728a", "uid": null, "qid": "e4340efb73e8468aaafa2db1a1c7c9bd", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [e4340efb73e8468aaafa2db1a1c7c9bd]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/app/main.py\", line 100, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 65, in Exec\n    return self.EXIT()\n  File \"/openfabric/app/app/Agent/Agent.py\", line 90, in EXIT\n    self.save_session()\n  File \"/openfabric/app/app/Agent/Agent.py\", line 106, in save_session\n    Agent._sessionsManager.save_session(\n  File \"/openfabric/app/app/Agent/SessionsManager.py\", line 55, in save_session\n    cls._db.save_session(username=username, session_id=session_id,image_desc=image_desc,history=cls._sessions[session_id],summary=summary)\n  File \"/openfabric/app/app/Agent/Storage/VectorDB.py\", line 40, in save_session\n    cls._vectorStore.save_session(session_id=session_id ,username = username ,summary=summary)\n  File \"/openfabric/app/app/Agent/Storage/VectorDB.py\", line 117, in save_session\n    cur.execute(\npsycopg2.errors.UndefinedTable: relation \"chat_index\" does not exist\nLINE 2:             INSERT INTO chat_index (session_id, username, em...\n                                ^\n\n", "created_at": "2025-06-30T16:30:22.711939"}], "status": "FAILED", "created_at": "2025-06-30T16:29:58.106051", "updated_at": "2025-06-30T16:30:22.712434", "finished": true}