{"sid": "885752b7155e4fe59516f358bd2623ca", "uid": null, "qid": "b4b705c1debd4e8fbbeeeb2abf19cd6c", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [b4b705c1debd4e8fbbeeeb2abf19cd6c]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 75, in Exec\n    resp = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 90, in exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 110, in process\n    parsed = json.loads(res)\n  File \"/usr/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Invalid control character at: line 1 column 449 (char 448)\n", "created_at": "2025-06-29T14:34:22.373384"}], "status": "FAILED", "created_at": "2025-06-29T14:34:16.857861", "updated_at": "2025-06-29T14:34:22.373447", "finished": true}