{"sid": "a132d4052ac649d19010c3b45d529f6f", "uid": null, "qid": "ff7298e428f44875b074e532df699e91", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [ff7298e428f44875b074e532df699e91]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/app/main.py\", line 100, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 59, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 73, in exec\n    llm_response = self.llm.prompt(user_prompt)\nAttributeError: 'NoneType' object has no attribute 'prompt'\n", "created_at": "2025-06-30T16:51:21.833541"}], "status": "FAILED", "created_at": "2025-06-30T16:51:03.159935", "updated_at": "2025-06-30T16:51:21.833578", "finished": true}