{"sid": "011ab9618ed74491ac7713bf742a66c9", "uid": null, "qid": "6307bb0da53f483f8c88447bf5262231", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [6307bb0da53f483f8c88447bf5262231]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 95, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 78, in Exec\n    return self.message,self.image,self.object,self.session_id\nAttributeError: 'Agent' object has no attribute 'message'\n", "created_at": "2025-06-28T13:04:44.949643"}], "status": "FAILED", "created_at": "2025-06-28T13:04:26.443752", "updated_at": "2025-06-28T13:04:44.949892", "finished": true}