{"sid": "8985bf14caa14d3dad0d6b60431002ea", "uid": null, "qid": "d719a774a16548c38a3d57433bea56d9", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [d719a774a16548c38a3d57433bea56d9]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 71, in Exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 111, in process\n    elif state == States.READ_MEM:\n  File \"/usr/lib/python3.8/enum.py\", line 384, in __getattr__\n    raise AttributeError(name) from None\nAttributeError: READ_MEM\n", "created_at": "2025-06-28T12:44:13.202937"}], "status": "FAILED", "created_at": "2025-06-28T12:43:55.895548", "updated_at": "2025-06-28T12:44:13.202992", "finished": true}