{"sid": "952f15bcaf6a4e15bc44ce50ca4c47db", "uid": null, "qid": "b4a889cd62b143639a46cd9444deb5ef", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [b4a889cd62b143639a46cd9444deb5ef]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 68, in Exec\n    return self.return_data()\n  File \"/openfabric/app/Agent/agent.py\", line 108, in return_data\n    return sd.message ,sd.image , sd.object ,sd.session_id\nAttributeError: 'SessionData' object has no attribute 'image'\n", "created_at": "2025-06-30T10:46:15.810562"}], "status": "FAILED", "created_at": "2025-06-30T10:46:07.244789", "updated_at": "2025-06-30T10:46:15.810598", "finished": true}